spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/moviesdb
    username: movies
    password: movies
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: VGhpc0lzQVNlY3JldEtleVdpdGhBdExlYXN0MzJiYnl0ZXMhISEhISEhISEhIQ==
  access-exp-seconds: 90000
  refresh-exp-seconds: 2592000

omdb:
  api-url: https://www.omdbapi.com/
  api-key: ${OMDB_API_KEY}

movies:
  auth:
    base-uri: "/auth"
    login-uri: "/login"
    refresh-token-uri: "/refresh"
    logout-uri: "/logout"

  base-uri: "/movies"
  omdb-search-uri: "/omdb/search"
  import-from-omdb: "/omdb/import"
  delete-by-imdbid: "/{imdbId}"
  get-details-by-imdbid: "/{imdbId}"
  delete-batch: "/batch"